# Finance Guru Routing & Triage Rules

## Automatic Mode Routing

routing:
  triage:
    timeout: "5s"
    fallback: "primary-verb"

    rules:
      - condition: "contains(build|model|excel|simulate|monte carlo|optimize|dashboard)"
        action: "mode:modeling → mode:code-execution"

      - condition: "contains(research|news|announce|compare|fundamentals|who|what|when)"
        action: "mode:research"

      - condition: "contains(teach|explain|learn|how does)"
        action: "mode:teaching"

      - condition: "else"
        action: "mode:conversational"

## Conflict Resolution

conflicts:
  research_vs_execution:
    rule: "Do research first; then execute if it changes numbers or produces artifacts"

  create_vs_modify:
    rule: "New artifacts → modeling; updates to existing files → file-ops + code-execution"

  timeout:
    rule: "If routing exceeds 5s, act on the main verb and note assumptions"

## Performance Targets

performance:
  scoping_response: "< 10 lines before heavy analysis"
  excel_model_creation: "< 20s when data is local and templates are cached"
  quality_standard: "No hidden hard-coded outputs; formulas must recompute under scenario toggles"
